permalink:           pretty
plugins: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

title:               Holden Caulfield
tagline:             ''
description:         ''
url:                 http://nlholden.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Holden Caulfield
  url:               https://github.com/nlholden
  email:             holden.caulfield4471@gmail.com

# Custom vars
version:             1.0.0
theme: minima

minima:
  skin: dark