theme: minima
permalink: pretty
plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 5
  permalink: /blog/page/:num/
  title: ':title - page :num'
  trail:
    before: 2
    after: 2
  sort_field: 'date'
  sort_reverse: true

title: Holden Caulfield
description: ''
url: http://nlholden.github.io
baseurl: ''
version: 1.0.0
future: true